#pragma once
#include <winsock2.h>
#include <WS2tcpip.h>
#include <Windows.h>
#include <d2d1.h>
#include <dwrite.h>
#include <wincodec.h>
#include <tchar.h>
#include <iostream>
#include <vector>
#include <list>
#include <stack>
#include <queue>
#include <map>
#include <xaudio2.h>
#include <process.h>
#include <mmsystem.h>

#include "coreMacro.h"
#include "Types.h"
#include "D2D1Core.h"
#include "Bitmap.h"
#include "ResourceManager.h"
#include "SceneManager.h"
#include "Network.h"